/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save your game': '保存游戏',
    'Singularity': '奇点',
    'Singularity Level': '奇点等级',
    'Objectives': '目标',
    'Options': '选项',
    'Ordinals': '序数',
    'per second': '每秒',
    'HACKER!!!': '黑客！！！',
    'How to play': '玩法',
    'Markup': '无限',
    'Markup Autobuyer: ON': '无限自动购买者：开启',
    'Markup Autobuyer: LOCKED': '无限自动购买者：已锁定',
    'Challenge': '挑战',
    'Challenges': '挑战',
    'Collapse': '坍缩',
    'Color: OFF': '颜色: 关闭',
    'Colors: ON': '颜色: 开启',
    'Colors: OFF': '颜色: 关闭',
    'Cost': '成本',
    'Currently': '当前',
    'Exit Challenge': '退出挑战',
    'Export your game file': '导出存档',
    'Factor': '因子',
    'Factors': '因子',
    'Extend Incrementy': '解锁拓展增幅',
    'Import your game file': '导入存档',
    'To Incrementy': '递增',
    'Unlock Challenges': '解锁挑战',
    'Incrementy': '增幅',
    'Unlock autoclicker for maxing all': '解锁自动点击全部最大',
    'incrementy multiplier': '增幅乘数',
    'Increase Ordinal by': '按序增加',
    'Need': '需要',
    'Music: OFF': '音乐: 关闭',
    'Millisecond Interval': '毫秒间隔',
    'Maximize ordinal, but number does not increase': '最大化序数，但数量不增加',
    'Reach Base': '购买进制数',
    'Buy ℵ': '购买 ℵ',
    'Hotkeys: ON': '热键: 开',
    'Hotkeys: OFF': '热键: 关',
    'Current Theme: Light': '当前主题:亮',
    'Dark Manifolds': '黑暗流形',
    'Dark Upgrades': '黑暗升级',
    'Do a Factor Shift (S': '进行因子转换（S',
    'Dynamic Factors': '动态因子',
    'Flashing Incrementy Reminder: ON': '闪烁增幅提醒:开',
    'Flashing Incrementy Reminder: OFF': '闪烁增幅提醒:关',
    'Factor Shift Autoprestiger: ON': '因子转换自动转生:开',
    'Factor Shift Autoprestiger: OFF': '因子转换自动转生:关',
    'Offline Progress: ON': '离线进度:开',
    'Offline Progress: OFF': '离线进度:关',
    'Perform a Factor Boost': '执行因子提升',
    'Perform a Factor Shift': '执行因子转换',
    'Max All (M': '全部最大 (M',
    'Max Mode: OFF': '最大模式: 关',
    'Max Mode: ON': '最大模式: 开',
    'Max All Autobuyer: LOCKED': '全部最大购买者: 锁定',
    'Max All Autobuyer: ON': '全部最大购买者: 开',
    'Boosters': '助推器',
    'Assign all': '全部分配',
    'Assign': '分配',
    'Autobuyers': '自动购买者',
    'Autoclickers': '自动点击者',
    'Autoprestigers': '自动转生者',
    'Booster Upgrades': '助推器升级',
    'Buy half of max ℵ': '购买最大值一半的 ℵ',
    'Unlock the next layer': '解锁下一层',
    'Unlock the Singularity': '解锁奇点',
    'Upgrades': '升级',
    'When you Factor Shift, you gain a new factor and the base decreases by': '当您进行因子转换时，您将获得一个新因子，并且进制数减少了',
    'When this happens, Decrementy increases very rapidly, the "Halve Decrementy Growth"': '发生这种情况时，递减非常迅速地增加，即“减半递减增长”',
    'RESET YOUR GAME': '删除存档',
    'Game autosaves every ten seconds': '游戏每十秒自动保存',
    'Each Factor is twice as powerful': '每个因子效果提升两倍',
    'Gain 5x as much OP': '序数点获取提高5倍',
    'Unlock Markup autoclicker': '解锁自动点击无限',
    'Gain 20 OP per second': '每秒获得20序数点',
    'Boosters boost Tier 1 and 2 automation by x': '使T1和T2的自动化提高',
    'You\'re currently not in a challenge': '你现在不在挑战内',
    'Autoclicker costs scales a lot worse, and you gain 125x the passive OP if you have the 5x OP upgrade': '自动点击价格大幅上涨,如果你购买了5倍序数点升级,你的自动生产序数点可以获得125倍效果',
    'You can\'t buy factors, Challenge 1 multiplier is useless': '你不能购买因子,挑战1的加成无效',
    'The base is 5 higher, all free factors are doubled (doesn\'t affect challenge mults': '基础进制提高5,所有免费因子都被翻倍(不受挑战加成',
    'Factor Shifts don\'t reduce the base': '因子转换不会降低进制',
    'You can do a maximum of 2 factor shifts': '你只能进行两次因子转换','Complete a Challenge': '完成一次挑战',
    'Unlock Incrementy': '解锁增幅',
    'Get four Extended Incrementy Upgrades': '获得增幅递增升级',
    'Reach 10240 to Markup': '到达10240以无限',
    'Autobuy Booster Upgrades: ON': '自动购买助推器升级：开',
    'Autobuy Booster Upgrades: OFF': '自动购买助推器升级：关',
    'Aleph Power': '阿列夫能量',
    'Collapse Autoprestiger: OFF': '坍缩自动转生者：关闭',
    'Collapse Autoprestiger: ON': '坍缩自动转生者：开启',
    'Cost: ??': '成本：??',
    'Current Theme: Dark': '当前主题：黑暗',
    'Current Theme: Space (https://wallpaperplay.com/page-terms': '当前主题：太空（https://wallpaperplay.com/page-terms',
    'Music: Going Down by Jake Chudnow': '音乐:杰克·查德诺的《沉沦》',
    'Music: Horizon by Scott Buckley (': '音乐:斯科特·巴克利的《地平线》(',
    'Music: Hypnothis by Kevin Macleod': '音乐:凯文·麦克劳德的《催眠》',
    'Power (+': '能量 (+',
    'Unlock Darkness': '解锁黑暗',
    'Get a Dark Manifold': '得到一个黑暗流形',
    'Halve decrementy growth below ω^(ω3), otherwise double it': '将递减增长减半到ω^（ω3）以下，否则将其增加一倍',
    'Ignore the 73 Booster Upgrade unless in Challenge 4, 6, or 7: ON': '忽略73助推器升级，除非在挑战4,6或7：开启',
    'Ignore the 73 Booster Upgrade unless in challenge 4, 6, or 7: OFF': '忽略73助推器升级，除非在挑战4,6或7：关闭',
    'Reset incrementy for a manifold.': '重置流形的增幅。',
    'REMEMBER TO CHECK INCREMENTY UPGRADES!!!': '记得检查增幅升级!!',
    'Redacted': '修订',
    'Reach the BHO to Collapse!': '达到BHO坍缩!',
    'Obtain one of each Aleph': '每个基数都有一个',
    'boosts Tier 2 by': '提升T2',
    'Complete the challenge!': '完成这个挑战!',
    'Complete all of the sluggish milestones': '完成所有缓慢的里程碑',
    'Translated to a x51 multiplier to Factor Boosts and a raise of cap to psi(w^w^w': '转换一个 x51 的倍数到因子的增加和提高上限到psi(w^w^w)',
    'Reach Level 20 Singularity': '达到20级奇点',
    'Reach level 20 Singularity': '达到20级奇点',
    'However, this started to end on a fateful day,': '然而，这一切开始在决定性的一天结束，',
    'However climbing the tower had a twist,': '然而，爬上塔顶有一个转折，',
    'Manifold': '流形',
    'The Tower of Infinity: a tale told throughout the lands,': '无限之塔：一个传遍整个土地的故事，',
    'The World is upon for a crude awakening': '这个世界正在经历一场残酷的觉醒',
    'There is 1 decrementy': '衰减1',
    'Unlock Dark Upgrades in the Markup Tab': '在无限选项卡中解锁黑暗升级',
    'This work is licensed under the': '该作品是根据',
    'This feature isn\'t implemented yet though': '该功能尚未实现',
    'Autocomplete Challenges: ON': '自动完成挑战：开启',
    'Autocomplete Challenges: OFF': '自动完成挑战：关闭',
    'Subscribe to Superspruce!': '订阅Superspruce !',
    'Sluggish Milestones': '缓慢的里程碑',
    'You are currently bulking in a set of': '您目前累计可因子转换 ',
    'YOU HAVE COLLAPSED!': '你已经坍缩！',
    'Upgrade with': '升级',
    'Reach g': '达到 g',
    ' ON': ' 开启',
    ' OFF': ' 关闭',
    ', Currently': ', 目前',
    'Your Dynamic Multiplier is': '您的动态倍数为',
    'Dynamic Factors reset on Infinities': '动态因子在无限时重置',
    'You\'re currently running Challenge': '您当前正在运行挑战',
    'Refund Confirmation: ON': '回退确认：开启',
    'Refund Confirmation: OFF': '回退确认：关闭',
    'Factor Boost if possible on Refund: OFF': '如果可能的话，回退时因子提升：关闭',
    'Factor Boost if possible on Refund: ON': '如果可能的话，回退时因子提升：开启',
    'Reach the BHO to collapse!': '到达BHO坍缩！',
    'Reduce Dark Manifold requirement scaling': '减少黑暗流形需求比例',
    'Reduce manifold requirement scaling': '减少流形需求比例',
    'Reduce the potency of decrementy by': '减少衰减的效力',
    'Time to wait until collapse in seconds': '等待坍缩的时间，以秒为单位',
    'You start gaining incrementy when you reach ψ(': '你开始获得增幅当你到达 ψ(',
    'You start gaining incrementy when you reach ψ(Ω': '你开始获得增幅当你到达 ψ(Ω',
    'Bulk Boosting: ON': '批量增强：开启',
    'Bulk Boosting: OFF': '批量增强：关闭',
    'boosts the ℵ': '提升 ℵ',
    'and Incrementy': '和增幅',
    'boosts Dynamic Factor Cap': '提高动态因子上限',
    ', but they reset on Factor Boosts and similar': '，但它们会在因子提升和类似功能上重置',
    'Raise Incrementy multiplier to the': '将增幅倍数提高到',
    'Double production of incrementy': '增幅产量加倍',
    'Double the OP gain from Infinities': '无限的OP收益翻倍',
    'Distribute All Cardinals': '分配所有基数',
    'Collapsing (Doesn\'t work offline': '坍缩(离线不起作用',
    'Complete the collapse in the required amount of Factor Boosts or less to recieve a prize!': '减少完成坍缩所需的因子提升数量，以获得奖励!',
    'boosts Incrementy gain': '提升增幅获得',
    'Multiply Incrementy multiplier by': '增幅的倍数乘以',
    'You get 3 free factors each': '您的每一个因子将获得免费的3个',
    'The base is always five below ψ(Ω). Buying this resets your ordinal': '进制数在ψ(Ω)以下始终为5. 购买这个重置你的序数',
    'The base is always five below ψ(0). Buying this resets your ordinal': '进制数在ψ(0)以下始终为5. 购买这个重置你的序数',
    'Markup gives 666666x OP if the base is less than six': '如果进制数小于6，则无限会提供666666x OP',
    'The above upgrade applies to passive OP gain': '上面的升级也对被动序数点获得有效',
    'ALL PREVIOUS CHALLENGES AT ONCE,': '以上所有挑战同时进行, ',
    'Gain 5x as much ': '获得5倍的',
    'In odd numbered challenges, Dynamic factor is squared': '在奇数挑战中，动态因子变为原来的平方',
    'Dynamic decreases 1.00e299 times slower': '动态降低1.00e299倍慢',
    'The base is reduced by 4 if it\'s over 7. Buying this resets your ordinal': '当进制数超过7时减少4. 购买这个重置你的序数',
    '  Challenges can be completed up to 3 times, each one giving a bigger reward.': '挑战最多可以完成3次，每次挑战都会获得更大的奖励。',
    'Achievements': '成就',
    'Progress in the game to earn achievements! They don\'t give any boost and are purely for bragging': '在游戏中取得进度来得到成就! 他们没有任何加成，只是用来炫耀',
    'Your current Ordinal Level is': '你现在的序数等级是',
    'Next Ordinal Level is at': '下一个序数等级在',
    'Your highest Ordinal Level is': '你最高的序数等级是',
    'and Challenge 6 Completions boost OP gain from Markups': '并且挑战6完成次数增加无限获得的序数点',
    'Double the production of incrementy': '增幅产量加倍',
    'Dynamic increases 100x faster': '动态因子增长速度变为100倍',
    'Manifolds are 26% more effective': '流形比原来有效26%',
    'Dynamic Factor Cap multiplies incrementy gain': '动态因子上限增加增幅产量',
    'Extra Factors': '额外因子',
    'Your Dynamic Factor is': '你的动态因子是',
    'Dynamic Factors reset on Markups': '动态因子在无限时重置',
    'Your Quadrupler is': '你的四倍器是',
    'maximize autoclickers': '最大自动点击者',
    'clicking the maximize button': '点击最大按钮',
    'You gotta start somewhere': '你必须从哪里开始',
    'Maximizable': '可最大化',
    'Markupable': '可无限',
    'Hyperdimensional': '超维度',
    'Ordinal Collapsing Functions': '序数坍缩函数',
    'Ackermann Ordinal': '阿克曼序数',
    'Double Ackermann Ordinal': '双倍阿克曼序数',
    'The Bachmann Howard Ordinal': '巴赫曼·霍华德序数',
    'To the BHO and Beyond!': '飞越BHO, 浩瀚无垠!',
    'Ackermann\'s BHO': '阿克曼的BHO',
    'I\'ve been Multiplied!': '我被加倍了!',
    '100 Ordinal Points is a lot': '100序数点很多',
    'Illuminati Confirmed!': '光明会确认!',
    'Left and Right 3 Factors': '求生之因子',
    '5 Factor Ordinal Punch': '因子5之拳',
    'Luck Related Achievement': '幸运的成就',
    'Faster than a potato': '比土豆更快',
    'Faster than a hundred potatoes': '比一百个土豆更快',
    'Faster than a square potato': '比土豆的平方更快',
    'Boost!': '提升!',
    'Booster Pack': '推进器套装',
    'Super Boost': '超级提升',
    'Collapsing Boosts': '坍缩提升',
    'ONE HUNDRED BOOSTS': '一百个提升',
    'GAS': '一鼓作气',
    'GAS GAS': '神清气爽',
    'GAS GAS GAS': '一身正气',
    'GAS GAS GAS GAS': '气象万千',
    'Not a fart achievementt': '不是放屁的成就',
    'Easy': '简单',
    'Medium': '中等',
    'Hard': '困难',
    'Difficult': '更难',
    'Challenging': '有挑战性',
    'Brutal': '残酷',
    'The Challenging Day': '挑战的一天',
    'Two Challenging Days': '挑战的两天',
    'Collapsing Challenges': '坍缩的挑战',
    'Impossible, or is it?': '不可能...吗?',
    'The first of mani': '许多中的第一个',
    'Two Colors': '两种颜色',
    'Four Suits': '四件西装',
    'Man, I Fold Cards': '李友星',
    'My Suit is better than yours': '我的西装比你的好',
    'Red Card!': '红牌!',
    'A Stacked Deck': '一副牌',
    'After all this time, you’re Still Immature!?!?': '图样图森破',
    'what is with all of these deck jokes?': '这些扑克笑话该适可而止了',
    '(hardcapped)': '(硬上限)',
    'The Singular Cardinal': '一个基数',
    'The Benefits of Codependence': '相互依赖的好处',
    'The Deep Dark': '深邃的黑暗',
    'Wait, there’s more than 4 upgrades?': '等下, 有超过四个升级?',
    'Always has been': '一向都是',
    'The Power of Two': '2的幂',
    'No Ethical Consumption': '恬不知耻的消费',
    'These Challenges aren’t dimensions': '这些挑战不是维度',
    'As easy as falling over': '像摔倒一样简单',
    'Not as easy as falling over': '不像摔倒一样简单',
    'Costco sells Challenges now!': '开市客现在出售挑战!',
    'The Factor Engine': '因子引擎',
    'Won’t need to click 100,000 times': '不需要点100000次',
    'All Your Sluggish Are Belong To Us': '你的所有缓慢里程碑都属于我',
    'Back to basics': '回到基础',
    'Slider goes brrrrrrrrrrrr': '滑块 brrrrr',
    'I Assure You It’s Quite Based': '我向你保证这很基础',
    'All Your Baseless Are Belong To Us': '你的所有无进制里程碑都属于我',
    'A Soulless Singularity': '一个孤独的奇点',
    'A Functioning Singularity': '奇点函数',
    'The answer to life, black holes, and everything': '一切的答案',
    'How Immature?': '图样图森破 II',
    'The Great Centurion': '伟大的百夫长',
    '200: OK': '200: 好的',
    '404: SINGULARITY NOT FOUND': '404: 奇点未找到',
    '420 Blaze It': '420的烈火',
    'Enter the E': '进入Z',
    'Infinitely Challenging': '无尽的挑战',
    'Double Trouble': '双倍的麻烦',
    'Oh Baby a Triple!': '哦, 三倍!',
    'How did pi get here?': 'π是如何来到这里的?',
    'Cinco de Mayo': '五月五日',
    'Subliminal': '潜意识',
    'Superliminal': '超意识',
    'The Challenging Eternity': '永恒的挑战',
    'Redundancy': '冗余',
    '(softcapped)': '(软上限)',
    'Welcome to the E': '欢迎来到增幅宇宙',
    'E for exponential': 'Z的含义是指数',
    'Double Exponential!': '双重指数!',
    'Triple Exponential!!!': '三重指数!!!',
    'R.I.P. balancing': '安息吧, 平衡',
    'Way too much': '太多了',
    'Export your game save via file': '通过文件导出你的存档',
    'Export your game save via text': '通过文本导出你的存档',
    'Import your game save via text': '通过文本导入你的存档',
    'You keep all Incrementy Upgrades, Dark Upgrades, Manifolds, and Dark Manifolds on collapse, unlock an Autobuyer for Booster Upgrades, you can autocomplete Challenges, unlock an Autoprestiger for Collapse, you get a free Maximize Autobuyer and you always have a Max All Autobuyer, you can complete Challenge 8 multiple times, reduce the Markup requirement to 10, Auto-Markup activates if you\'re not making autoclicks from Tier 1, unlock two incredibly powerful Aleph upgrades and four Booster upgrades': '你在坍缩时保留所有的增幅升级, 黑暗升级, 流形和黑暗流形, 解锁因子转换和因子提升自动购买者, 可以自动完成挑战, 解锁自动坍缩者, 获得免费的最大化自动点击者, 并且始终拥有全部最大自动点击者,  您可以完成多于3次挑战8, 将无限需求减少到10, 无限自动点击者在T1自动化不工作时触发, 解锁两个功能强大的阿列夫升级和四个助推器升级',
    'Downgrade the Singularity for a Manifold': '下降一级奇点以获得一个流形',
    'Pick two challenges and play in them. You can\'t complete any challenges and Factors are useless. You can buy booster upgrades, even in challenge 6+': '选择两个挑战进入, 你不能完成任何挑战, 因子不起作用. 你可以购买推进器升级, 即使在挑战6+中',
    'Current Reward: Complete all challenges 3 times per completion^1.4, up to most ever completed.': '当前奖励: 完成所有挑战(3*完成次数^1.4)次, 上限为曾经最多完成次数.',
    'All doublings are disabled. You also can\'t enter even numbered challenges': '所有加倍均被禁用, 你不能进入偶数号挑战.',
    'Booster upgrades are disabled': '推进器升级被禁用',
    'Factor Shifts and the second Incrementy upgrade are much more expensive': '因子转换和第二个增幅升级变得更贵',
    'You can\'t normally buy Singularity Functions upgrade and the Singularity is stuck at 1. You also can\'t enter normal challenges': '你不能购买奇点函数, 奇点等级被固定在1. 你不能进入挑战',
    'Reward: Aleph power is stronger': '奖励: 阿列夫能量变得更强',
    'Exit Omega Challenge': '退出欧米伽挑战',
    'Enter Omega Challenge Confirmation: OFF': '进入欧米伽挑战确认: 关',
    'Enter Omega Challenge Confirmation: ON': '进入欧米伽挑战确认: 开',
    'Exit Omega Challenge Confirmation: OFF': '退出欧米伽挑战确认: 关',
    'Exit Omega Challenge Confirmation: ON': '退出欧米伽挑战确认: 开',
    'Perform Double Collapse upon entering an Omega Challenge: OFF': '进入欧米伽挑战时双重坍缩: 关',
    'Perform Double Collapse upon entering an Omega Challenge: ON': '进入欧米伽挑战时双重坍缩: 开',
    'If you want a greater understanding of how the ordinal works, you might want to watch this': '如果您想进一步了解序数的工作原理，则可以观看Vsauce的这段视频',
    'by Vsauce explaining how to count past infinity': ', 解释如何数到无穷之后',
    'Oh, and also, if you like this game, or you dislike the timewalls, why don\'t you play': '哦, 而且, 如果您喜欢这款游戏，或者您不喜欢等待, 那么为什么不玩',
    'It has more content below ψ(Ω) and you can reach': '它在ψ(Ω)以下有更多的内容, 您可以达到',
    'Oh, and why not you join the': '哦, 为什么不加入',
    'You have': '你有',
    'manifolds, translating to a': '个流形, 造成',
    '\nYet over hundreds of years, undefeated it still stands.': '然而几百年过去了，它仍然屹立不倒。',
    '\nAnd the amount of layers ever so tall.': '以及如此之多的层次。',
    '\nOnly to find the exact same climb once more.': '只为再次找到完全相同的攀登。',
    '\nSoon seen by any who entered its mist;': '很快就被任何进入雾中的人看见;',
    '\nThe reward at the end is infinite power,': '最终的回报是无限的力量，',
    '\nThe stairs on each floor were far too small,': '每层楼的楼梯都太小了，',
    '\nThey started climbing and reached the second floor,': '他们开始往上爬，来到二楼，',
    '\nWhen there was a visitor who would come to stay.': '当有客人要来的时候。',
	', otherwise double it': '以下, 否则加倍',
    'Gain 15 OP per second, Markup requirement is now 100, and you can bulk complete challenges': '每秒获得15序数点, 无限的需求降低至100, 并且你可以一次性完成多次挑战',
	'Refund all Singularity Functions': '回退所有奇点函数',
	'Start. Singularity doesn\'t consume Dark Manifolds': '开始. 奇点不消耗黑暗流形',
	'Manifolds affect Decrementy gain': '流形对衰减获得有效',
	'Second row of Incrementy applies to Dark Manifolds': '第二行增幅升级对黑暗流形有效',
	'Third row of Incrementy applies to Decrementy': '第三行增幅升级对衰减有效',
	'Unlock the Portal': '解锁传送门',
	'You found an easter egg! Good job!': '你找到了一个彩蛋! 好!',
	'Unlock Baseless Milestones': '解锁无基数里程碑',
	'You can reach w^w4 in challenge 8, but in base 5 only': '你可以在挑战8中达到ω^(ω4), 但仅在5进制',
	'Square root the fourth Factor Shift cost': '第4次因子转换的花费变为原来的平方根',
	'Good luck': '祝你好运',
	'Unlock Incrementy Doubler autobuyer': '解锁增幅产量加倍自动购买者',
	'Quadruple OP and Decrementy from all sources': '序数点和衰减变为四倍',
    'Goal reached!': '目标已达成!',
    'Infinity': '无限',
    'OR restart the current Collapse': '或重启当前坍缩',
    'It is also decreasing by': '它也递减了',
    'Factor Boosts per second': '每秒因子提升',
    'When the universe ends, a world out there is waiting to be explored.': '当宇宙终结的时候，外面的世界正等着我们去探索。',
    'Note: In challenge 8, if you have less than 1.00e10 decrementy, all ticks simulates 50 milliseconds, regardless of the millisecond interval.': '注意:在挑战8中，如果衰减小于1.00e10，那么所有计时都模拟50毫秒，而不管毫秒间隔是多少。',
    'Multiply multiplier by': '倍数乘以',
    'Next boost in bulk will take <': '下一次批量提升将 <',
    'OFF': '关闭',
    'ON': '打开',
    'Oh, and you die lol': '哦，你死了，哈哈',
    'rdinal Markup Factor Shift Edition Minus?': '序号标记因子转换版是否为负？',
    'Owned': '拥有',
    'production': '生产',
    'Reach blah blah blah to unlock the next row of achievements!': '达到blah blah blah解锁下一排成就!',
    'Your Markup Autobuyer is useless because Markups no longer exist': '您的标记自动购买器无用，因为标记不再存在',
    'Your last Factor Shift was 1 second ago [WIP]': '您上一次的因子转换是1秒前[WIP]',
    'Your last Markup was 1 second ago [WIP]': '您上一次标记是1秒前[WIP]',
    'Your highest Ordinal was w [WIP]': '您最高的序数是w [WIP]',
    'Your Factor Boost Autoprestiger is Factor Boosting 1 time per second': '你的因子提升自动转生者是每秒提升1次因子',
    'Your factors are multiplying your autoclickers by': '您的因子乘以你的自动点击者',
    'Your Factor Shift Autoprestiger is Factor Shifting 1 time per second': '你的因子转换自动转生者是每秒转换1次因子',
    'Manifolds are instantly sacrificed to the Singularity': '流形立即被牺牲为奇点',
    'Ordinal Markup Factor Shift Edition Minus?': '序数标记因子偏移版是否为负？',
    'Gain an additional incrementy multiplier per incrementy doubler upgrade based on unspent functions': '根据未使用的功能，每次增量倍增器升级获得一个额外的增量乘数',
    'Fractal Dimensional Base': '分形维度基础',
    'Fractal Engine': '分形引擎',
    'Fractal Shifts give a x': '分形位移给出了一个x',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    //原样
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
	'Manifolds are buffed. (x^4)': '流形效果是原来的4次方',
	'Multiply Aleph Power Multipliers by 1.5': '阿列夫倍数乘以1.5',
	'Singularity effect is raised to the 1.4': '奇点效果是原来的1.4次方',
	//'Reduce': '降低',
	'Each unspent function increases ': '每个未使用的函数将',
	//'Your': '你的',
    'Aleph Power': '阿列夫能量',
    'Aleph Upgrades': '阿列夫升级',
    'Baseless Milestones': '无进制里程碑',
    'Downgrade to lvl 1': '下降到1级',
    'Singularity Functions': '奇点函数',
    'Omega Challenges': '欧米伽挑战',
    'Omega Challenge': '欧米伽挑战',
    'Completed： ': '完成次数: ',
    'Currently': '当前',
    'Aleph power is stuck at x0.0001': '阿列夫能量被固定在x0.0001',
    'Reward: Factor Shifts are much cheaper everywhere you go, ': '无论你在哪里, 因子转换变得更加便宜',
    'Reward: Raise base incrementy gain to the': '奖励: 增幅产量^',
    'Current Reward: Boost all doubling to ': '当前奖励: 提升所有加倍至',
    'Reward: The left column of Booster upgrades are much cheaper (cost^0.5^x)': '奖励: 第一列推进器升级变得更加便宜 (价格^(0.5^完成次数))',
    'When you enter an Omega Challenge, the factor boost multiplier from Singularity doesn\'t work. You also lose your Double Incrementy production upgrades, but you\'ll get them back after you exit the challenge.\n            Omega Challenges can be completed a fractional number of times past 1.': '当你进入欧米伽挑战时, 奇点等级不起作用. 你还会丢失增幅生产加倍升级, 但在退出挑战后会返回. 欧米伽挑战可以完成大于1的任意实数次. ',
    'Each prize also starts you with an extra': '每个里程碑还给你一个额外的',
	'Halve decrementy growth below ': '衰减增长减半于',
	'Gain a 1.2x multiplier to Tier 1 and 2': '使T1和T2自动化速度变为原来的1.2倍',
    'Unmultiplied Pending OP speeds up decrementy by x^0.2': '判定中的序数点以0.2次方加快你的衰减',
	'Cost:': '花费: ',
	'  Cost:': '花费: ',
    'Buy Successor Autobuyer for': '购买后继自动购买者',
    'Buy Maximize Autobuyer for': '购买最大化自动购买者',
    ' successor autoclickers, clicking the successor button': '后继自动点击者, 点击后继按钮',
    ' maximize autoclickers, clicking the maximize button': '最大化自动点击者, 点击最大化按钮',
    'Base Incrementy multiplier is raised to the 1.05': '增幅的基础因数变为原来的1.05次方',
    'Manifolds are 3x as effective, and gain a flat 5e8/s Tier 2': '流形比原来有效两倍, 并且获得额外的5e8/s T2自动化速度',
    'Double the OP from Markups and gain a flat 1e15/s Tier 2': '无限获得双倍序数点, 并且获得额外的1e15/s T2自动化速度',
    'Base 6 is now base 5': '6进制现在是5进制',
    'Unlock Omega Challenges': '解锁欧米伽挑战',
    'You gain 1% of OP gained per second if your OP is less than your pending': '如果你的序数点低于判定中的序数点, 你每秒获得判定中的1%的',
    'Challenges 1-7 without completions give a reduced boost (x^0.25)': '未完成的挑战1~7给你一个被降低的加成(0.25次方)',
    'Current Version:': '当前版本: ',
    '  Last Updated:': '最后更新时间: ',
    'Dynamic drops by 1.00e300 per second, keep no OP on Markup, you can\'t buy Booster Upgrades, and you can do a maximum of 1000 manual successor clicks per Markup, Quadrupler is disabled': '动态因子每秒降低1e300, 无限时不保留序数点, 你不能购买推进器升级, 并且你每次无限中只能手动点击\"按序增加1\"按钮1000次, 四倍器被禁用',
    'There\'s exponentially rising decrementy dividing Tier 1 production, immediately Refund if you have any Booster Upgrades, all challenge effects are disabled, Challenge 7 completions boost OP, keep no OP on Markup, you can do a maximum of 1000 manual successor clicks per Markup, Quadrupler is disabled, ordinal is capped at w^(w3)': '有一个指数增加的衰减降低你的T1自动化速度, 在你购买任何推进器升级时立即回退, 所有挑战完成没有效果, 挑战7完成次数增加序数点获得, 无限不保留序数点, 并且你每次无限中只能手动点击\"按序增加1\"按钮1000次, 四倍器被禁用, 序数最高达到ω^(ω3)',
    'Sweet ': '甜蜜的',
    'We can\'t afford ': '我们无法承担',
    'scam': '骗局',
    'Hmm yes, the OP here is now': '是的, 序数点是现在的',
    'Achievements': '成就',
    ' large numbers (smaller than vanilla though)': '很大的数字(虽然比原版小)',
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    'Maximum Ordinal Length above': '序数长度限制, 当序数高于',
    'Maximum Ordinal Length below': '序数长度限制, 当序数低于',
    'Current Ordinal Notation:': '数组显示方式：',
    'Your factors are multiplying Tier 1 Automation by': '你的因子使你的T1自动化倍数提高',
    'Your Max All Autobuyer is clicking the Max All button': '你的自动购买全部最大将会以每秒',
    'Your Markup Autobuyer is clicking the Markup button': '你的自动无限将会以每秒',
    'You have no factors. Perform a Factor Shift to get one!': '你还没有因子，进行一次因子转换来获得一个！',
    'Your 0 challenge completions have multiplied Tier 1 and 2 Automation by': '你完成的0次挑战使你的T1和T2自动化提高',
    'Your 1 challenge completions have multiplied Tier 1 and 2 Automation by': '你完成的1次挑战使你的T1和T2自动化提高',
    'Your 2 challenge completions have multiplied Tier 1 and 2 Automation by': '你完成的2次挑战使你的T1和T2自动化提高',
    'Your 3 challenge completions have multiplied Tier 1 and 2 Automation by': '你完成的3次挑战使你的T1和T2自动化提高',
    'Your 4 challenge completions have multiplied Tier 1 and 2 Automation by': '你完成的4次挑战使你的T1和T2自动化提高',
    'Your 5 challenge completions have multiplied Tier 1 and 2 Automation by': '你完成的5次挑战使你的T1和T2自动化提高',
    'Your 6 challenge completions have multiplied Tier 1 and 2 Automation by': '你完成的6次挑战使你的T1和T2自动化提高',
    'Your 7 challenge completions have multiplied Tier 1 and 2 Automation by': '你完成的7次挑战使你的T1和T2自动化提高',
    'Your 8 challenge completions have multiplied Tier 1 and 2 Automation by': '你完成的8次挑战使你的T1和T2自动化提高',
    'Your 9 challenge completions have multiplied Tier 1 and 2 Automation by': '你完成的9次挑战使你的T1和T2自动化提高',
    'Your 10 challenge completions have multiplied Tier 1 and 2 Automation by': '你完成的10次挑战使你的T1和T2自动化提高',
    'Your 11 challenge completions have multiplied Tier 1 and 2 Automation by': '你完成的11次挑战使你的T1和T2自动化提高',
    'Your 12 challenge completions have multiplied Tier 1 and 2 Automation by': '你完成的12次挑战使你的T1和T2自动化提高',
    'Your 13 challenge completions have multiplied Tier 1 and 2 Automation by': '你完成的13次挑战使你的T1和T2自动化提高',
    'Your 14 challenge completions have multiplied Tier 1 and 2 Automation by': '你完成的14次挑战使你的T1和T2自动化提高',
    'Your 15 challenge completions have multiplied Tier 1 and 2 Automation by': '你完成的15次挑战使你的T1和T2自动化提高',
    'Your 16 challenge completions have multiplied Tier 1 and 2 Automation by': '你完成的16次挑战使你的T1和T2自动化提高',
    'Your 17 challenge completions have multiplied Tier 1 and 2 Automation by': '你完成的17次挑战使你的T1和T2自动化提高',
    'Your 18 challenge completions have multiplied Tier 1 and 2 Automation by': '你完成的18次挑战使你的T1和T2自动化提高',
    'Your 19 challenge completions have multiplied Tier 1 and 2 Automation by': '你完成的19次挑战使你的T1和T2自动化提高',
    'Your 20 challenge completions have multiplied Tier 1 and 2 Automation by': '你完成的20次挑战使你的T1和T2自动化提高',
    'Your 21 challenge completions have multiplied Tier 1 and 2 Automation by': '你完成的21次挑战使你的T1和T2自动化提高',
    'Your 22 challenge completions have multiplied Tier 1 and 2 Automation by': '你完成的22次挑战使你的T1和T2自动化提高',
    'Your 23 challenge completions have multiplied Tier 1 and 2 Automation by': '你完成的23次挑战使你的T1和T2自动化提高',
    'Your 24 challenge completions have multiplied Tier 1 and 2 Automation by': '你完成的24次挑战使你的T1和T2自动化提高',
    'Challenge Confirmation:': '挑战确认:',
    'Factor Boost if possible on entering a Challenge:': '如果可能的话，进入挑战时因子提升:',
    'Reward: Dynamic Factor Cap boosts Tier 1 and 2': '奖励:动态因子上限增强自动化T1和T2',
    'Challenges can be completed up to 3 times, each one giving a bigger reward.': '每个挑战最多可以完成三次,每次完成都会提供更大的加成',
    'Factor Shift (0): Requires 200 OP': '因子转换(0):需要200序数点',
    'Factor Shift (1): Requires 1000 OP': '因子转换(1):需要1000序数点',
    'Factor Shift (3): Requires 350000 OP': '因子转换(3):需要350000序数点',
    'Factor Shift (4): Requires 1.000e12 OP': '因子转换(4):需要1.000e12序数点',
    'Factor Shift (5): Requires 1.000e21 OP': '因子转换(5):需要1.000e21序数点',
    'Factor Shift (6): Requires 1.000e100 OP': '因子转换(6):需要1.000e100序数点',
    'Factor Shift (2): Requires 10000 OP': '因子转换(2):需要10000序数点',
    'Factor Shift (7): Requires Infinity OP': '因子转换(7):需要Infinity序数点',
    'Factor Boost (1): Requires': '因子提升(1):需要',
    'Factor Boost (2): Requires': '因子提升(2):需要',
    'Factor Boost (3): Requires': '因子提升(3):需要',
    'Factor Boost (4): Requires': '因子提升(4):需要',
    'Factor Boost (5): Requires': '因子提升(5):需要',
    'Factor Boost (6): Requires': '因子提升(6):需要',
    'Factor Boost (7): Requires': '因子提升(5):需要',
    'Factor Boost (8): Requires': '因子提升(8):需要',
    'Factor Boost (9): Requires': '因子提升(9):需要',
    'Factor Boost Confirmation:': '因子提升自动购买：',
    'Factor Boost if possible on Challenge:': '挑战中因子提升自动购买：',
    'Buy 3 Booster Upgrades': '购买3个助推器升级',
    '\n      ': '',
    'Raising the Factor Boosts 25+ requirement to ': '将因子提升25以上的需求提升到',
    'You are currently getting ': '你现在获得',
    'Each reward also starts you with an extra': '每个里程碑还给你一个额外的',
    'Gain 1 RP per second': '每秒获得1回退点',
    'You can now change the Singularity faster (max, min, slider) and autobuy singularity function upgrades': '你现在可以更快地改变奇点等级(最大化, 最小化, 滑块)和自动购买奇点函数升级',
    'Forever keep the first four function upgrades free and unlock advanced autoshift (Refunding is encouraged)': '前两行奇点函数升级保持免费(不会被回退), 并且解锁高级自动因子转换',
    'Automatically get Incrementy and Dark Manifolds and Upgrades without losing incrementy, (max cost of e600 Incrementy)': '自动获得流形, 黑暗流形, 增幅升级, 黑暗升级, 并不损失任何东西(上限为消耗1e600增幅)',
    'You can now enter any challenges past three completion!': '你现在可以在进入任何完成三次的挑战!',
    'Reach the required ordinal in Challenge 4 to receive a reward': '在挑战4中达到需要的序数来获得里程碑',
    'Manifolds boost Tier 2': '流形增强T2自动化',
    'Tier 1 autoclickers boost each other': 'T1自动化增强自己',
	'OP boosts Tier 1 and 2 by': '序数点使得T1和T2自动化变为',
	'Gain 3% of most cardinals gained at once per second': '每秒获得一次获得的最多基数的3%',
	'Keep 10% of Factor Boosts on Collapse': '坍缩时保留10%因子提升',
	'Unlock Challenge 9': '解锁挑战9',
    'Most Cardinals collapsed at once:': '一次坍缩获得的最多基数',
    'Get your ordinal to ω^ω^ω': '使你的序数达到ω^ω^ω',
    'Reach the number': '达到序数',
    'Perform an Markup': '进行一次无限',
    'Buy a Factor': '购买一个因子',
    'You are getting': '你可以获得',
    'You have': '你有',
    'Need': '需要',
    'Goal:': '目标:',
    'Markup to gain': '点击无限，以获得',
    'Collapse Confirmation: ON': '坍缩确认: 开',
    'Collapse Confirmation: OFF': '坍缩确认: 关',
    'Tier 3 Automation (Works Offline)': 'T3自动化 (离线时有效)',
    'Remove Darkness': '移除黑暗',
    'Remove Factor Boosts': '移除因子提升',
    'Remove Factors': '移除因子',
    'Remove Omega Challenges': '移除欧米伽挑战',
    'Remove the ability to Markup (you can still gain 1% of passive pending OP per second': '删除标记功能（您仍然可以每秒获得1％的被动挂起序数点的权限）',
    'Remove Booster Upgrades': '移除助推器升级',
    'Remove Autoprestigers': '移除自动转生者',
    'Remove Challenges': '移除挑战',
    'Remove Aleph Power': '移除阿列夫能量',
    'Perform Double Collapse upon entering Omega Challenge: ': '进入欧米茄挑战赛时进行两次坍缩：',
    'x multiplier to Dynamic Factor Cap only': 'x 乘数仅适用于动态因子上限',
    'Remove Collapsing': '移除坍缩',
    'Remove the Dynamic Factor': '移除动态因子',
    'Remove the Quadrupler': '移除四倍器',
    'Unlock Fractal Boosts': '解锁分形提升',
    'Unlock Fractal Engine Upgrades': '解锁分形引擎升级',
    'Unlock Fractal Shifts': '解锁分形移位',
    'Unlock Incrementy Multiplier autobuyer': '解锁增量乘数自动购买器',
    'Unlock Incrementy Power autobuyer': '解锁增量能量自动购买器',
    'Unlock the Fractal Engine': '解锁分形引擎',
    'Unlock the next set of Omega Challenges!': '解锁下一组欧米伽挑战！',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
}

//需处理的后缀
var cnPostfix = {
    'times per second, but only if you\'re past ψ(0). It also activates if your Tier 1 automation isn\'t autoclicking at least once a second': '次每秒, 但仅当你的序数大于等于ψ(0). 它也在你的T1自动化速度小于1次每秒时生效',
    'times per second, but only if you\'re past ψ(Ω). It also activates if your Tier 1 automation isn\'t autoclicking at least once a second': '次每秒, 但仅当你的序数大于等于ψ(Ω). 它也在你的T1自动化速度小于1次每秒时生效',
    'times per second, but only if you\'re past ψ(Ω×1). It also activates if your Tier 1 automation isn\'t autoclicking at least once a second': '次每秒, 但仅当你的序数大于等于ψ(Ω×1). 它也在你的T1自动化速度小于1次每秒时生效',
	'Functions': '奇点函数',
	'Dark Manifold singularity scaling to x4.': '黑暗流形奇点乘数至x4. ',
	'singularity scaling to x30.': '奇点乘数至x30',
	'multiplier divides Challenge 8 goals': '倍数降低挑战8目标',
	'effect by 40%': '的效果增加40%',
	'(cap at 1.1 completions)':'(上限为1.1)',
    'Your Decrementy is multiplying by': '你的衰减乘以',
    'You have': '你有',
    'Import your game save via file (will overwrite save)': '通过文件导入你的存档(会覆盖存档)',
    'Game autosaves every ten seconds': '游戏每十秒自动保存一次(假的, 容易丢档, 建议导出保存)',
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    " ": "",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    'incrementy per second': '增幅每秒',
    'times per second, but only if you can\'t Factor Shift': '次的速度点击,只会在你无法进行因子转换时启动',
    'times per second, but only if you\'re past ψ(Ω×1': '次的速度点击,只会启动当你序数点超过ψ(Ω×1',
    '\n      ': '',
    'times the Factor Boosts': '次因子提升',
    'Challenge Completions': '次挑战完成',
    'Achievements': '成就',
    'Second set of Omega Challenges unlocked': '解锁第二组欧米伽挑战',
    'Unassigned Cardinals': '未分配的基数',
    ' (10) Ordinal Points (I)': '序数点 (I)',
    'time(s) per second, but only at the BHO or higher, and if you can\'t get a sluggish milestone': '次每秒, 但仅当序数大于等于BHO, 且你不能得到缓慢的里程碑',
    'time(s) per second': '次每秒',
    'Factor Boost Autoprestiger: OFF': '因子提升自动转生: 关',
    'Factor Boost Autoprestiger: ON': '因子提升自动转生: 开',
    'Advanced Autoshift (max of 5 Factor Shifts in Challenge 8): ON': '高级自动因子转换 (在挑战8中最多因子转换5次): 开',
    'Advanced Autoshift (max of 5 Factor Shifts in Challenge 8): OFF': '高级自动因子转换 (在挑战8中最多因子转换5次): 关',
    'factors are useless lol': '因子不起任何作用, 哈哈哈',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    'times per second': '次每秒',
    'Ordinal Points': '序数点',
    'OP': '序数点',
    '': '',
    '': '',
    '': '',
    '': '',
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^x?\d+(\.\d+)?[A-Za-z%]{0,2}(\s.C)?\s*$/, //12.34K,23.4 °C
    /^x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /^\s*$/, //纯空格
    /^\d+(\.\d+)?[A-Za-z]{0,2}.?\(?([+\-]?(\d+(\.\d+)?[A-Za-z]{0,2})?)?$/, //12.34M (+34.34K
    /^(\d+(\.\d+)?[A-Za-z]{0,2}\/s)?.?\(?([+\-]?\d+(\.\d+)?[A-Za-z]{0,2})?\/s\stot$/, //2.74M/s (112.4K/s tot
    /^\d+(\.\d+)?(e[+\-]?\d+)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?$/, //2.177e+6 (+4.01+4
    /^(\d+(\.\d+)?(e[+\-]?\d+)?\/s)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?\/s\stot$/, //2.177e+6/s (+4.01+4/s tot
];
var cnExcludePostfix = [
    /:?\s*x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /:?\s*x?\d+(\.\d+)?[A-Za-z]{0,2}$/, //: 12.34K, x1.5
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
var cnRegReplace = new Map([
	[/^Collapse for (.+) Cardinals \(C$/, '坍缩以获得 $1 基数 (C'],
    [/^Reach the BHO first to collapse! (.+) in collapse$/, '先到达BHO坍缩! $1 秒后坍塌'],
    [/^cap in base (.+)$/, '$1 进制中达到上限'],
    [/^Your (.+) challenge completions have multiplied Tier 1 and 2 Automation by (.+)$/, '你完成的 $1 次挑战将T1和T2自动化加快 $2 倍'],
    [/^Increase Factor (.+) for (.+) OP$/, '增加因子 $1 花费 $2 OP'],
    [/^Reward: Factor (.+) boosts Tier (.+) and$/, '奖励：因子 $1 增强自动化T $2 和T'],
    [/^You have (.+) boosters$/, '您有$1个助推器'],
    [/^Markup to gain (.+) Ordinal Points \(I$/, '点击无限，以获得 $1 序数点 \(I'],
    [/^Unlock Distribute All and upgrades for Tier (.+) automation$/, '解锁全部分发功能并升级 T$1 自动化'],
    [/^Unlock Tier (.+) automation, the (.+) booster upgrade is improved$/, '解锁 T$1 自动化，$2 助推器升级被改进'],
    [/^Increase Factor (.+) for$/, '提升因子 $1 '],
    [/^Tier (.+) Automation$/, 'T$1 自动化'],
    [/^(\d+)d (\d+)h (\d+)m$/, '$1 小时 $2 分钟 $3 秒'],
    [/^Ignore in challenge (.+): ON$/, '忽略挑战$1：开启'],
    [/^Ignore in Challenge (.+): ON$/, '忽略挑战$1：开启'],
    [/^per second\n(.+)$/, '每秒'],
    [/^\n(.+)Your Decrementy is multiplying by$/, '你的衰减乘以'],
    [/^\n(.+)You have$/, '你有'],
    [/^\n(.+)Challenges can be completed up to 3 times, each one giving a bigger reward.$/, '挑战最多可以完成3次，每次挑战都会获得更大的奖励。'],
    [/^\n(.+)For the one who is able to ascend this tower.$/, '对于能够登上这座塔的人。'],
    [/^x multiplier to Dynamic Factor output and cap\n(.+)$/, 'x 倍数以动态因子输出和上限'],
    [/^Translated to a\n(.+)$/, '转换为一个'],
    [/^Gain (.+) Boosters \(B$/, '获得 $1 助推器 \(B'],
    [/^Gain (.+) Factor Boosts \(B$/, '获得 $1 次因子提升 \(B'],
    [/^Cost: (.+) ℵ$/, '成本: $1 ℵ'],
    [/^Goal: (.+) OP$/, '目标：$1 OP'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^ (.+) times per second, but only if you're past ψ\($/, '$1 次数每秒，但仅当您经过 ψ\('],
    [/^ (.+) cardinal$/, '$1 基数'],
    [/^ (.+) successor autobuyers$/, '$1 继任自动购买者'],
    [/^ (.+) maximize autobuyers$/, '$1 最大化自动购买者'],
    [/^ (.+) boosters$/, '$1 推进器'],
    [/^ (.+) ℵ$/, '$1 ℵ'],
    [/^Reach (.+) to Markup$/, '达到 $1 以标记'],
    [/^Next Cardinal in (.+) Factor Boost\(s\) \((.+)s in collapse$/, '下一个基数在 $1 因子提升\(秒\) \($2秒 崩溃'],
    [/^ (.+) Boosters and (.+) Challenge Completions$/, '$1 助推器和完成 $2 个挑战'],
    [/^ (.+) times per second, but only if you're past ψ\(Ω$/, '$1 次数每秒，但仅当您超过ψ\(Ω'],
    [/^ (.+) incrementy, multiplying Tier (.+) Automation by$/, '$1 增幅，T$2 自动乘以'],
    [/^You are currently getting (.+) Factor Boosts per second$/, '您目前每秒获得 $1 因子提升'],
    [/^Tier 3 Automation Upgrades$/, 'T $1 自动升级'],
    [/^Refund back (.+) boosters, but reset all factor shifts$/, '退还 $1 助推器，但重置所有因子转换'],
    [/^Refund back (.+) boosters, but reset all factor shifts \(R$/, '退还 $1 助推器，但重置所有因子转换 \(R'],
    [/^You\'re currently in Challenge (.+).$/, '您目前正在挑战 $1。'],
    [/^It is increasing by (.+) per second$/, '每秒增加 $1'],
    [/^It is increasing by (.+) per second and caps at$/, '每秒增加 $1 并且上限为'],
    [/^Factor Boost (.+): Requires g$/, '因子提升 $1：需要 g'],
    [/^(.+) to see when you can boost!$/, '$1 看看什么时候可以提升！'],
    [/^ (.+)  maximize autoclickers, clicking the maximize button$/, '$1 最大化自动点击者，点击最大化按钮'],
    [/^ (.+) successor autoclickers, clicking the successor button$/, '$1 后继自动点击者，点击后继按钮'],
    [/^([\d\.,]+) Boosts$/, '$1 提升'],
    [/^([\d\.,]+) Boost$/, '$1 提升'],
    [/^You should be getting a total of (.+) Factor Boost\(s\) per second$/, '您应该每秒获得总计 $1 的因子提升'],
    [/^Perform a Factor(.+) Boosts$/, '执行一个因子提升'],
    [/^(.+) Boosters$/, '$1 助推器'],
    [/^(.+) Booster$/, '$1 助推器'],
    [/^(.+) Incrementy$/, '$1 递增'],
    [/^(.+) Factor Boosts per second$/, '$1 因子提升每秒'],
    [/^: (.+) Decrementy$/, ': $1 衰减'],
    [/^: (.+) mult$/, ': $1 加成'],
    [/^Buy Maximize Autobuyer for (.+)  OP$/, '购买最大化自动购买者成本为$1 OP'],
    [/^Buy Maximize Autobuyer for (.+) OP$/, '购买最大化自动购买者成本为$1 OP'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],
]);